# Generated by Django 5.2.4 on 2025-07-23 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_userpreference_preferred_categories'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpreference',
            options={'verbose_name_plural': 'User Preferences'},
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='preferred_category',
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='preferred_category',
            field=models.ManyToManyField(blank=True, related_name='preferred_by_users', to='news.category'),
        ),
    ]
