# Generated by Django 5.2.4 on 2025-07-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_userpreference_preferred_categories'),
        ('users', '0002_alter_userpreference_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_category',
            field=models.ManyToManyField(to='news.category'),
        ),
    ]
