# Generated by Django 5.2.4 on 2025-07-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_userpreference_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_categories',
            field=models.ManyToManyField(blank=True, related_name='preferred_by_news_users', to='news.category'),
        ),
    ]
