# Generated by Django 5.2.4 on 2025-07-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_readinghistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='Unknown Source', max_length=255),
        ),
    ]
