# Generated by Django 5.2.4 on 2025-07-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
