# Generated by Django 5.2.4 on 2025-07-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
