# Generated by Django 5.2.4 on 2025-07-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_article_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(related_name='multi_articles', to='news.category'),
        ),
    ]
