# Generated by Django 5.2.4 on 2025-08-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_article_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='news_audio/'),
        ),
    ]
