# Generated by Django 5.2.4 on 2025-08-01 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_alter_article_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='source_url',
        ),
    ]
